version: '3'

volumes:
  messageq_data: {} 
services:
  messageq:
    image: 'messageq:localv1'
    container_name: messageq 
    environment:
      - MQ_SERVER_PORT=8081
      - MQ_BROKER_RETRY_BACKOFF_BASE=30s 
      - MQ_BROKER_RETRY_BACKOFF_MULTIPLIER=2.0
      - MQ_BROKER_RETRY_BACKOFF_MAX=1800s
      - ETCD_ENABLE_V2=true  
    ports:
      - 8081:8081 
    volumes:
      - messageq_data:/app/data